export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const GET_SHOWS_REQUEST = 'GET_SHOWS_REQUEST';
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const GET_SHOWS_FAILURE = 'GET_SHOWS_FAILURE';

export const GET_MOVIESHOWDETAIL_REQUEST = 'GET_MOVIESHOWDETAIL_REQUEST';
export const GET_MOVIESHOWDETAIL_SUCCESS = 'GET_MOVIESHOWDETAIL_SUCCESS';
export const GET_MOVIESHOWDETAIL_FAILURE = 'GET_MOVIESHOWDETAIL_FAILURE';
